### ISSUE TITLE
Time complexity of floor_sum

### ISSUE THREAD

**Issue by rsk0315** [atcoder/ac-library#101]
The document says `O(log(m+a))`, but now (by https://github.com/atcoder/ac-library/pull/92) `m+a` may be negative or zero. I suggest `O(log(a mod m))`.

By the way, maybe, its complexity could be bounded by `O(log(min(n, a mod m)))`. It might be wrong because I guessed just intuitively (and empirically). So I'm glad if anyone can analyze this.

**Comment by rsk0315** [comment]
Oh. Obviously, `a mod m` may be zero. 😢

How about `O(log((a mod m)+1))`?

**Comment by rsk0315** [comment]
`O(log(1))` equals `O(0)`, which is not suitable.
`O(max(1, log((a mod m)+1)))`, `O(log((a mod m)+2))`, or something like that? 😥

... Or, just `O(log(m))`?

**Comment by yosupo06** [comment]
Just O(log m) is enough
