### ISSUE TITLE
docs: add summarized (human-friendly) description to "crt"

### ISSUE THREAD

**Issue by rdrgn** [atcoder/ac-library#103]
[Math](https://atcoder.github.io/ac-library/production/document_ja/math.html)のcrtにある説明から常人が「中国の剰余定理」という名称（あるいはCRTが何の略か）に辿り着くには（コンテストの成績を左右するには十分に長い）時間が掛かるのではないかと思います。

> ## crt
> 
> ```cpp
> pair<ll, ll> crt(vector<ll> r, vector<ll> m)
> ```
> 
> 同じ長さの配列 $r, m$ を渡します。この配列の長さを $n$ とした時、
> 
> $$x \equiv r[i] \pmod{m[i]}, \forall i \in \lbrace 0,1,\cdots, n - 1 \rbrace$$
> 
> を解きます。答えは(存在するならば) $y, z (0 \leq y < z = \mathrm{lcm}(m[i]))$ を用いて $x \equiv y \pmod z$ の形で書けることが知られており、この $(y, z)$ をpairとして返します。答えがない場合は $(0, 0)$ を返します。$n=0$ の時は $(0, 1)$ を返します。

**Comment by yosupo06** [comment]
「CRT algorithm」「CRT atcoder」「CRT codeforces」のどれで検索しても1ページ目に出てきたので、大丈夫だと思います
