### ISSUE TITLE
Declaring several methods in atcoder::segtree as const

### ISSUE THREAD

**Issue by hitonanode** [atcoder/ac-library#106]
I want to append `const` to several method declarations in `atcoder::segtree`.

Some complicated DP problems require to maintain two segtrees to improve time complexity. In such situations, coders always have to pay attention to them. If one of them is not modifed at all (used like (disjoint) sparse tables), I want to declare it as `const` to reduce the risk of updating the wrong segtree.

In current ACL, all `atcoder::segtree` methods are not declared as `const`, so we cannot declare the instances as `const` when there is no update query. On the other hand, it seems that the methods `get()`, `prod()`, `all_prod()`, `max_right()` and `min_left()` do not affect any member variables. I suggest that these methods have `const` like [this](https://github.com/hitonanode/ac-library/commit/8de49c6f150d2e5af851cbbd074aee552bf2bec9) to enable such usage of `atcoder::segtree`.

What do you think of this modification?

**Comment by yosupo06** [comment]
The situation that your suggested makes sense for me.

Otherhand, we have a concern about your modification: If `segtree.prod()` is const whereas `lazysegtree.prod()` isn't const, it may be confusing.

Probably we can solve those problems by `mutable` or `const_cast` or something, but I haven't checked yet.

**Comment by hitonanode** [comment]
Thanks for comments, @yosupo06. I understood the concern on the consistency of interface, and tried writing const-friendly lazy_segtrees. I first wrote [the one using `mutable` ](https://github.com/hitonanode/ac-library/commit/060f9e6f2e82043a6eda028df8ebd2b69f2a62fb), which is simple but might be accused of abusing `mutable`. I then wrote [another one using `const_cast`](https://github.com/hitonanode/ac-library/commit/a8f81a90ee87384526ff7d81cb877b43bdf621b7#diff-5cbae82e51663c6fa4abc9d8dd99a4ccdf6535cb712da341644abe73f7f45347), which perhaps requires a little knowledge of pointers to readers. What type of modification (or do nothing) is more preferable for ACL (Lazy) Segtrees?

Below are the `lazy_segtree` submissions for some problems on OJs. Though it may be obvious, it seems that no constant factor degradation is observed because of these modifications.
| Problem | Used methods | Plain lazy_segtree | mutable | const_cast |
| ---- | ---- |  ---- | ---- | ---- |
| [AC practice2-K](https://atcoder.jp/contests/practice2/tasks/practice2_k) | `prod()`, `apply()` | [GCC, 866 ms](https://atcoder.jp/contests/practice2/submissions/20131799) / [Clang, 927 ms](https://atcoder.jp/contests/practice2/submissions/20131803) | [GCC, 835 ms](https://atcoder.jp/contests/practice2/submissions/20131884) / [Clang, 797 ms](https://atcoder.jp/contests/practice2/submissions/20131885) | [GCC, 881 ms](https://atcoder.jp/contests/practice2/submissions/20135044) / [Clang, 861 ms](https://atcoder.jp/contests/practice2/submissions/20135046) |
| [AC practice2-L](https://atcoder.jp/contests/practice2/tasks/practice2_l) | `prod()`, `apply()` | [GCC, 265 ms](https://atcoder.jp/contests/practice2/submissions/20131919) / [Clang, 231 ms](https://atcoder.jp/contests/practice2/submissions/20131922) | [GCC, 267 ms](https://atcoder.jp/contests/practice2/submissions/20131932) / [Clang, 234 ms](https://atcoder.jp/contests/practice2/submissions/20131936) | [GCC, 263 ms](https://atcoder.jp/contests/practice2/submissions/20135096) / [Clang, 239 ms](https://atcoder.jp/contests/practice2/submissions/20135101) |
| [AC ACLBC-E](https://atcoder.jp/contests/abl/tasks/abl_e) | `prod()`, `apply()` | [GCC, 252 ms](https://atcoder.jp/contests/abl/submissions/20135245) / [Clang, 245 ms](https://atcoder.jp/contests/abl/submissions/20135251) | [GCC, 245 ms](https://atcoder.jp/contests/abl/submissions/20135299) / [Clang, 238 ms](https://atcoder.jp/contests/abl/submissions/20135302) | [GCC, 246 ms](https://atcoder.jp/contests/abl/submissions/20135334) / [Clang, 239 ms](https://atcoder.jp/contests/abl/submissions/20135340)
| [CF 555C](https://codeforces.com/contest/555/problem/C) | `get()`, `apply()` | [GNU C++17 (64), 592 ms](https://codeforces.com/contest/555/submission/107255996) | [GNU C++17 (64), 576 ms](https://codeforces.com/contest/555/submission/107256161) | [GNU C++17 (64), 577 ms](https://codeforces.com/contest/555/submission/107256207) |
| [TOKI troc17F](https://tlx.toki.id/problems/troc-17/F) | `apply()`, `max_right()` | [C++17, 138 ms](https://tlx.toki.id/problems/troc-17/F/submissions/780524) | [C++17, 141 ms](https://tlx.toki.id/problems/troc-17/F/submissions/780526)| [C++17, 145 ms](https://tlx.toki.id/problems/troc-17/F/submissions/780612) |

**Comment by yosupo06** [comment]
Thanks for your careful investigation. I feel `mutable` is better.
