### ISSUE TITLE
documents of segtree.min_left and lazysegtree.min_left are wrong

### ISSUE THREAD

**Issue by naminodarie** [atcoder/ac-library#11]
https://github.com/atcoder/ac-library/blame/master/document_en/segtree.md#L155
https://github.com/atcoder/ac-library/blame/master/document_ja/segtree.md#L159
https://github.com/atcoder/ac-library/blame/master/document_en/lazysegtree.md#L165
https://github.com/atcoder/ac-library/blame/master/document_ja/lazysegtree.md#L166

English:
I guess `g(op(a[l - 1], a[l + 1], ..., a[r - 1])) = false` should be `g(op(a[l - 1], a[l], ..., a[r - 1])) = false`.

Japanese:
`g(op(a[l - 1], a[l + 1], ..., a[r - 1])) = false`は`g(op(a[l - 1], a[l], ..., a[r - 1])) = false`の誤りではないでしょうか。

**Comment by yosupo06** [comment]
Thanks! / そのとおりです、ありがとうございます
