### ISSUE TITLE
Dinic algorithm seems to have an unnecessary variable

### ISSUE THREAD

**Issue by iensen** [atcoder/ac-library#110]
https://github.com/atcoder/ac-library/blob/08ac6c1e6af564fa54d58512b9e73a03e4bdc58a/atcoder/maxflow.hpp#L71

Why do you need the "iter" variable in maxflow.hpp? It seems it is only initialized to 0 and never changed.

**Comment by yosupo06** [comment]
https://github.com/atcoder/ac-library/blob/08ac6c1e6af564fa54d58512b9e73a03e4bdc58a/atcoder/maxflow.hpp#L94

We are using `iter` in this line

**Comment by iensen** [comment]
I don't follow. iter[v]  is always equal to 0. Why do you need it there, just use 0 instead!
