### ISSUE TITLE
MaxFlow documentation is odd

### ISSUE THREAD

**Issue by NachiaVivias** [atcoder/ac-library#128]
## [1] `$flow_limit$`

日本語版の関数 `flow` の (2) の説明中にあります。変な表示をします。 MinCostFlow の関数 `min_cost_max_flow` にも対応する部分がありますが、こちらでは `` `flow_limit` `` となっています。

## [2] flow の英語版

関数 `flow` の (2) の説明が英語版にはありません。

**Comment by yosupo06** [comment]
ありがとうございます！
