### ISSUE TITLE
Add more translation of the documents

### ISSUE THREAD

**Issue by EarthMessenger** [atcoder/ac-library#134]
AtCoder Library is pretty great! But it's not easy for programmers around the world to read and understand the document. To promote the library, I hope we can have more translations of the documents.

PS: I'm translating Chinese documents.

**Comment by yosupo06** [comment]
Thanks for suggesting.

We currently only plan to publish English & Japanese document in this repository because we cannot maintain documents in other languages.

However, we recently decided to publish our documents as CC0 license. Please feel free to translate and publish it, thanks!
