### ISSUE TITLE
Got "Segmentation fault" while using <atcoder/convolution>

### ISSUE THREAD

**Issue by danielsun3164** [atcoder/ac-library#135]
My program at https://atcoder.jp/contests/abc214/submissions/30708618 got "Segmentation fault".
gdb shows following:
`Program received signal SIGSEGV, Segmentation fault.`
`atcoder::internal::butterfly<atcoder::static_modint<1000000007, (void*)0>, (void*)0> (a=std::vector of length 2048, capacity 2048 = {...}) at ../../../include/atcoder/convolution.hpp:107`
`107	                    rot *= info.rate3[bsf(~(unsigned int)(s))];`
My program worked after I changed line 65, as https://atcoder.jp/contests/abc214/submissions/30709044
Am I using in a wrong way?

**Comment by yosupo06** [comment]
We cannot use convolution with mod 10^9 + 7. Please refer this comment https://github.com/atcoder/ac-library/issues/124#issuecomment-913659725

**Comment by danielsun3164** [comment]
Thank you very much for your comment. I understand.
