### ISSUE TITLE
[Question] Is constraint f(e) = true   really necessary for max_right?

### ISSUE THREAD

**Issue by KeiichiHirobe** [atcoder/ac-library#146]
Doc of `max_right`/`max_left`  in `segtree`/`lazy_segtree` says as below.

https://github.com/atcoder/ac-library/blob/master/document_en/segtree.md?plain=1#L135
https://github.com/atcoder/ac-library/blob/master/document_en/lazysegtree.md?plain=1#L145

But, as far as I read source code, `max_right`/`max_left` doesn't need Constraint `f(e) = true`.(Maybe I'm missing something)
Why does `max_right`/`max_left` need  this constrint?

**Comment by yosupo06** [comment]
The reason we added this constraint is that it is unclear what value we should return when `f(e()) = false`.

The main usage of `max_right` function is for monotone `f`, as we wrote in doc.

```
If `f` is monotone, this is the maximum `r` that satisfies `f(op(a[l], a[l + 1], ..., a[r - 1])) = true`.
```

And in this explanation, ... what value should we return? `l - 1`? At least our current implementation may returns `l` but it doesn't make sense.
