### ISSUE TITLE
Deduplicate segments with the same tangent properly on mcf_graph::slope

### ISSUE THREAD

**Issue by MiSawa** [atcoder/ac-library#37]
This line doesn't seem to be correct me. Instead, we should update this variable by `d`.
Also, it would be better to name it `cost_per_flow` or something like that to avoid confusion.
https://github.com/atcoder/ac-library/blob/a32a17b200e064162c22e2c818e07b173d857114/atcoder/mincostflow.hpp#L146

A test case would be
```cpp
TEST(MincostflowTest, SameCostPaths) {
    mcf_graph<int, int> g(3);
    ASSERT_EQ(0, g.add_edge(0, 1, 1, 1));
    ASSERT_EQ(1, g.add_edge(1, 2, 1, 0));
    ASSERT_EQ(2, g.add_edge(0, 2, 2, 1));
    auto expected = std::vector<std::pair<int, int>>{{0, 0}, {3, 3}};
    ASSERT_EQ(expected, g.slope(0, 2));
}
```

**Comment by yosupo06** [comment]
Thanks! Yes, this is a bug clearly.
