### ISSUE TITLE
The document at GitHub Pages is old

### ISSUE THREAD

**Issue by kmyk** [atcoder/ac-library#41]
The document at GitHub Pages of this repository is tracking `production` branch. Is this intended?
I recommend to use `master` for GitHub Pages, or make clear what branches are used (e.g. use https://atcoder.github.io/ac-library/production/document_en/ as the URL).

For example, the fix for https://github.com/atcoder/ac-library/issues/2 is merged into `master` but not merged into `production` yet, and the document at GitHub Pages is still wrong.

**Comment by yosupo06** [comment]
We changed the URL so that it contains branch/tag name (In later, we'll change the link of README)
