### ISSUE TITLE
Using pragma once instead of include guards

### ISSUE THREAD

**Issue by svaderia** [atcoder/ac-library#42]
Instead of having `#ifndef` to guard against the multiple includes, `#pragma once` can be used. Looks a bit cleaner that way.

**Comment by yosupo06** [comment]
Thanks for suggesting!

Yes, `#pragma once` is more clear way to write include guard, but we use `#ifndef` Intentionally. `#pragma once` isn't C++ standard (https://en.wikipedia.org/wiki/Pragma_once ). We don't use non-standard function if there is no special reason.
