### ISSUE TITLE
Minimum cost flow algorithm

### ISSUE THREAD

**Issue by guestname** [atcoder/ac-library#56]
Hello.

Is there any place I can learn about the minimum cost flow algorithm which is in the library?

Edit: Actually, it seems to be the same algorithm in [this topcoder tutorial](https://www.topcoder.com/community/competitive-programming/tutorials/minimum-cost-flow-part-two-algorithms/). However, they claim the complexity is O(nmFlogn) instead of O(F(n+m)logn). Which one should I trust? xD

**Comment by yosupo06** [comment]
AtCoder doesn't publish any resources to learn minimum cost flow algorithm. I guess there are many usefull lecture notes, books or something becuase minimum cost flow algorithm is quite famous.

Our time complexity is correct, O(F(n+m)logn).

**Comment by yosupo06** [comment]
#57 I notice the time complexity is wrong (not O(F(n+m)logn), but O(F(n+m)logm))... thanks!
