### ISSUE TITLE
Documentation for MacOS (Visual Studio specifically)

### ISSUE THREAD

**Issue by mkagenius** [atcoder/ac-library#69]
The documentation currently have instructions for Visual Studio on Windows (see path in the doc with C drive, I don't know where the include folder is in macOS case). I guess most of the programmers use Windows and hence the lack of documentation on MacOS. I had tried to set it up a few weeks back and had a great trouble in getting it compiled in Visual studio. (Command line compile is fine but visual studio doesn't see the library). 

It will be helpful for macOS users.

**Comment by rishabhdeepsingh** [comment]
you can add the `atcoder` library folder to your `include` folder then it should be working fine.

**Comment by rishabhdeepsingh** [comment]
create a file named `.vscode/c_cpp_properties.json` at your root project and then add the following content into it. make sure to change the `ac-library` to your path.

```json
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/Users/username/path/to/ac-library/*"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/local/bin/gcc-10",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by rishabhdeepsingh** [comment]
now it works fine. see there are no error squiggle lines.
<img width="306" alt="Screenshot 2021-01-19 at 4 18 17 AM" src="https://user-images.githubusercontent.com/28526643/104968992-645fb280-5a0d-11eb-9782-943fb7df1b2c.png">

**Comment by yosupo06** [comment]
TBH, editor-specific settings are too hard for supporting officially. I want to expect it to the community.
