### ISSUE TITLE
wrong links in index.md

### ISSUE THREAD

**Issue by Golovanov399** [atcoder/ac-library#8]
All `#include <atcoder/...>` links in the `index.md` lead to `something.html`, while it should be `something.md` I guess.

**Comment by yosupo06** [comment]
This is intended. For making the pages of https://atcoder.github.io/ac-library/document_en/,  we convert `xxx.md` into `xxx.html`, and links become to work correctly.

**Comment by Golovanov399** [comment]
Oh ok, I wasn't aware of this website and it is not crucial then, but I think it'd be better if it contained `.md` links initially and then you also converted the internal links, not only renamed the files. I don't know the details, but to me it doesn't seem very difficult.

Again, I think it's quite ok to leave it as it is, because it doesn't resolve the `@keyword.constraints` stuff in the github anyway.

**Comment by yosupo06** [comment]
We put the link of docs in `README.md`, so we think it is okay to left `.md` files as is.
