### ISSUE TITLE
Incorrect comment in math?

### ISSUE THREAD

**Issue by rsk0315** [atcoder/ac-library#93]
https://github.com/atcoder/ac-library/blob/c9838af67734e40c0a6d237f5349a25ec5ee9446/atcoder/math.hpp#L57

I think this should be:

```
x*u0*g % (u1*g) = (r1-r0) % (u1*g) (u0*g = m0, u1*g = m1)
```

For example, when `(r0, r1) = (4, 0)` and `(m0, m1) = (5, 3)`, we have `(x, g, u0, u1) = (-2, 1, 5, 3)`.  So `x*u0*g % (u1*g)` is `-1` (or `2` if we consider non-negative mod), but `(r1-r0)` is `-4`.

Anyway, the code itself seems correct.

**Comment by yosupo06** [comment]
I intended to "x*u0*g \equiv (r1-r0) (\bmod (u1*g)" here. So this comment is wrong, thanks!
